<a href="https://colab.research.google.com/github/arvindbishnoii/arvindbishnoii/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# installing devito and importing modules 
#!pip install devito
#!pip install sympy
#!pip install numpy
#!pip install matplotlib
#!pip install pandas
import numpy as np
import sympy as sp
import pandas as pd
from sympy import *
from devito import *
from numpy import *


#A=100
#alpha = symbols(u'α')           # birth rate
#beta_e = symbols(u'β_e')        # the asymptomatic contact rate
#beta_i = symbols(u'β_i')        # is the symptomatic contact rate
#theta= symbols (u'θ')
#phi_e = symbols (u'Φ_e')       #  is the asymptomatic recovery rate
#phi_r = symbols (u'Φ_r')       # is the infected recovery rate
#phi_d = symbols (u'Φ_d')       # is the infected mortality rate
#sigma = symbols (u'σ')       # the inverse of the incubation period
#mu = symbols (u'μ')          # is the general (non-COVID-19) mortality rate

# declaring diffusion paramters as 1 for trial

#V_s = symbols (u'V_s')
#V_e = symbols (u'V_e')
#V_i = symbols (u'V_i')
#V_r = symbols (u'V_r')

# lets taks Alee coefficient as 1 for trial

#A = symbols (u'A')



# creating a grid
grid = Grid(shape=(100,100), extent=(1,1))
grid
#grid1=Grid(shape(50), extent=(1))



# for creating time function

#susceptible (S), exposed (E), infected (I), Recovered (R) and Dead (D). 
#The system of equations in the SEIRD model is given by:
S = TimeFunction(name='S', grid=grid,space_order=1,time_order=1)

E = TimeFunction(name='E', grid=grid,space_order=1,time_order=1)

I = TimeFunction(name='I', grid=grid,space_order=1,time_order=1)

R = TimeFunction(name='R', grid=grid,space_order=1,time_order=1)

D = TimeFunction(name='D', grid=grid,space_order=1,time_order=1)

alpha=TimeFunction(name='alpha', grid=grid,time_order=1,save=1000)
beta=TimeFunction(name='beta', grid=grid,time_order=1,save=100)
Rep_num=TimeFunction(name='Rep_num', grid=grid,time_order=1,save=100)

#g.shape

N = S + E + I + R + D
N = TimeFunction(name='N', grid=grid,space_order=1,time_order=1)
# where N is the total population, i.e. N = S + E + I + R + D at each time t 

In [17]:
#Eq1=Eq(S.dt, - (D)/N * S* I)
#Eq1
#After giving some values to d,n,s,i

Eq1=Eq(S.dt, - (10)/50 * 20* 10)
Eq1

Eq(Derivative(S(t, x, y), t), -40.0000000000000)

In [18]:
from examples.seismic import TimeAxis

t0 = 0.  # Simulation starts a t=0
tn = 1000.  # Simulation last 1 second (1000 ms)
dt = 1.           # Time step from model grid spacing

time_range = TimeAxis(start=t0, stop=tn, step=dt)

In [19]:
stencil = solve(Eq1, S.forward)
update = Eq(S.forward, stencil)
update

Eq(S(t + dt, x, y), dt*(-40.0 + S(t, x, y)/dt))

In [20]:
stencil

dt*(-40.0 + S(t, x, y)/dt)

In [21]:
op = Operator(update, opt="noop")
op

Cpu64NoopCOperator[Kernel]<int; struct dataobj *,const float,const int,const int,const int,const int,const int,const int,struct profiler *>

In [22]:

op(time=20, dt=dt)

Operator `Kernel` ran in 0.01 s


PerformanceSummary([(PerfKey(name='section0', rank=None),
                     PerfEntry(time=0.00010500000000000005, gflopss=0.0, gpointss=0.0, oi=0.0, ops=0, itershapes=[]))])

In [24]:
S.data[20]

#value of s after 20 timestamps

Data([[-800., -800., -800., ..., -800., -800., -800.],
      [-800., -800., -800., ..., -800., -800., -800.],
      [-800., -800., -800., ..., -800., -800., -800.],
      ...,
      [-800., -800., -800., ..., -800., -800., -800.],
      [-800., -800., -800., ..., -800., -800., -800.],
      [-800., -800., -800., ..., -800., -800., -800.]], dtype=float32)

In [25]:
print(op.ccode)

#define _POSIX_C_SOURCE 200809L
#define START_TIMER(S) struct timeval start_ ## S , end_ ## S ; gettimeofday(&start_ ## S , NULL);
#define STOP_TIMER(S,T) gettimeofday(&end_ ## S, NULL); T->S += (double)(end_ ## S .tv_sec-start_ ## S.tv_sec)+(double)(end_ ## S .tv_usec-start_ ## S .tv_usec)/1000000;

#include "stdlib.h"
#include "math.h"
#include "sys/time.h"

struct dataobj
{
  void *restrict data;
  int * size;
  int * npsize;
  int * dsize;
  int * hsize;
  int * hofs;
  int * oofs;
} ;

struct profiler
{
  double section0;
} ;


int Kernel(struct dataobj *restrict S_vec, const float dt, const int time_M, const int time_m, const int x_M, const int x_m, const int y_M, const int y_m, struct profiler * timers)
{
  float (*restrict S)[S_vec->size[1]][S_vec->size[2]] __attribute__ ((aligned (64))) = (float (*)[S_vec->size[1]][S_vec->size[2]]) S_vec->data;

  for (int time = time_m, t0 = (time)%(2), t1 = (time + 1)%(2); time <= time_M; time += 1, t0 = (time)%(2), t1 = (time + 1)%(2))
  {


Model parameters estimation-


In [ ]:
# vector stack

a = np.array([[1], [2], [3]])
f = np.array([[1], [2], [3]])
rho = np.array([[1], [2], [3]])

stacked_vectors=np.vstack((a,f,rho))
stacked_vectors

i = np.array([[320], [396], [472]])
r = np.array([[24], [24], [32]])
d = np.array([[13], [16], [19]])

stacked_vectors1=np.vstack((i,r,d))
stacked_vectors1



array([[320],
       [396],
       [472],
       [ 24],
       [ 24],
       [ 32],
       [ 13],
       [ 16],
       [ 19]])

In [ ]:
a = np.array([1, 2, 3])
f = np.array([1, 2, 3])
rho = np.array([1, 2,3])

stacked_vectors=np.vstack((a,f,rho))
stacked_vectors

i = np.array([320, 396, 472])
r = np.array([24, 24, 32])
d = np.array([13, 16, 19])

stacked_vectors1=np.vstack((i,r,d))
stacked_vectors1



array([[320, 396, 472],
       [ 24,  24,  32],
       [ 13,  16,  19]])

In [ ]:
#perimeter estimation a,f,rho
'''
def u(v):
  a = np.array([1,2, 3])
  f = np.array([1, 2, 3])
  rho = np.array([1, 2, 3])
  v=np.vstack((a,f,rho))
  return v
'''
def fun_rosenbrock(x):
    return np.array([100 * x[0],5-x[1],5*x[2]])

#return np.array([10 * (x[1] - x[0]**2), (1 - x[0]) , (3 - x[2])])

from scipy.optimize import least_squares
i = np.array([320, 396, 472])
r = np.array([24, 24, 32])
d = np.array([13, 16, 19])
n = np.array([i[0],r[0],d[0]])
Y=np.vstack((i,r,d))
stacked_vectors1
res_1 = leastsq(fun_rosenbrock, n)
res_1

(array([-3.32053644e-33,  5.00000000e+00, -1.34887977e-34]), 2)

In [ ]:
from scipy.optimize import leastsq
def func(x):
    return 2*(x-3)**2+1
leastsq(func, 0)


(array([2.99999999]), 1)

In [ ]:
import numpy as np
from numpy import exp
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.special import factorial
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import statsmodels.api as sm
from statsmodels.api import Poisson
from scipy import stats
from scipy.stats import norm
from statsmodels.iolib.summary2 import summary_col

i = np.array([320, 396, 472])
r = np.array([24, 24, 32])
d = np.array([13, 16, 19])
 # x = np.array([320, 32, 19])
X=np.vstack((i[0],r[0],d[0]))

y = np.array([1, 2, 3])

stats_poisson = Poisson(y, X).fit()
print(stats_poisson.summary())

Optimization terminated successfully.
         Current function value: 1.824455
         Iterations 4
                          Poisson Regression Results                          
Dep. Variable:                      y   No. Observations:                    3
Model:                        Poisson   Df Residuals:                        2
Method:                           MLE   Df Model:                            0
Date:                Sat, 23 Jul 2022   Pseudo R-squ.:                 -0.2652
Time:                        22:07:12   Log-Likelihood:                -5.4734
converged:                       True   LL-Null:                       -4.3260
Covariance Type:            nonrobust   LLR p-value:                       nan
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0005      0.003      0.156      0.876      -0.005       0.006


In [ ]:
shape=(10,10)
be=np.empty(shape=shape )

# We can now write the PDE
S.dt =  -beta * 20 * 60 / 100
S.dt

-12*beta(time, x, y)

In [ ]:
df1=pd.read_csv('/content/dpc-covid19-ita-regioni new.csv')  
df1.head(50)

data stato  region_code                 region        lat  \
0   2020-02-24T18:00:00   ITA           13                Abruzzo  42.351222   
1   2020-02-24T18:00:00   ITA           17             Basilicata  40.639471   
2   2020-02-24T18:00:00   ITA           18               Calabria  38.905976   
3   2020-02-24T18:00:00   ITA           15               Campania  40.839566   
4   2020-02-24T18:00:00   ITA            8         Emilia-Romagna  44.494367   
5   2020-02-24T18:00:00   ITA            6  Friuli Venezia Giulia  45.649435   
6   2020-02-24T18:00:00   ITA           12                  Lazio  41.892770   
7   2020-02-24T18:00:00   ITA            7                Liguria  44.411493   
8   2020-02-24T18:00:00   ITA            3              Lombardia  45.466794   
9   2020-02-24T18:00:00   ITA           11                 Marche  43.616760   
10  2020-02-24T18:00:00   ITA           14                 Molise  41.557748   
11  2020-02-24T18:00:00   ITA           21           P.A. Bolzano  46.499335   
12  2020-02-24T18:00:00   ITA           22            P.A. Trento  46.068935   
13  2020-02-24T18:00:00   ITA            1               Piemonte  45.073274   
14  2020-02-24T18:00:00   ITA           16                 Puglia  41.125596   
15  2020-02-24T18:00:00   ITA           20               Sardegna  39.215312   
16  2020-02-24T18:00:00   ITA           19                Sicilia  38.115697   
17  2020-02-24T18:00:00   ITA            9                Toscana  43.769231   
18  2020-02-24T18:00:00   ITA           10                 Umbria  43.106758   
19  2020-02-24T18:00:00   ITA            2          Valle d'Aosta  45.737503   
20  2020-02-24T18:00:00   ITA            5                 Veneto  45.434905   
21  2020-02-25T18:00:00   ITA           13                Abruzzo  42.351222   
22  2020-02-25T18:00:00   ITA           17             Basilicata  40.639471   
23  2020-02-25T18:00:00   ITA           18               Calabria  38.905976   
24  2020-02-25T18:00:00   ITA           15               Campania  40.839566   
25  2020-02-25T18:00:00   ITA            8         Emilia-Romagna  44.494367   
26  2020-02-25T18:00:00   ITA            6  Friuli Venezia Giulia  45.649435   
27  2020-02-25T18:00:00   ITA           12                  Lazio  41.892770   
28  2020-02-25T18:00:00   ITA            7                Liguria  44.411493   
29  2020-02-25T18:00:00   ITA            3              Lombardia  45.466794   
30  2020-02-25T18:00:00   ITA           11                 Marche  43.616760   
31  2020-02-25T18:00:00   ITA           14                 Molise  41.557748   
32  2020-02-25T18:00:00   ITA           21           P.A. Bolzano  46.499335   
33  2020-02-25T18:00:00   ITA           22            P.A. Trento  46.068935   
34  2020-02-25T18:00:00   ITA            1               Piemonte  45.073274   
35  2020-02-25T18:00:00   ITA           16                 Puglia  41.125596   
36  2020-02-25T18:00:00   ITA           20               Sardegna  39.215312   
37  2020-02-25T18:00:00   ITA           19                Sicilia  38.115697   
38  2020-02-25T18:00:00   ITA            9                Toscana  43.769231   
39  2020-02-25T18:00:00   ITA           10                 Umbria  43.106758   
40  2020-02-25T18:00:00   ITA            2          Valle d'Aosta  45.737503   
41  2020-02-25T18:00:00   ITA            5                 Veneto  45.434905   
42  2020-02-26T18:00:00   ITA           13                Abruzzo  42.351222   
43  2020-02-26T18:00:00   ITA           17             Basilicata  40.639471   
44  2020-02-26T18:00:00   ITA           18               Calabria  38.905976   
45  2020-02-26T18:00:00   ITA           15               Campania  40.839566   
46  2020-02-26T18:00:00   ITA            8         Emilia-Romagna  44.494367   
47  2020-02-26T18:00:00   ITA            6  Friuli Venezia Giulia  45.649435   
48  2020-02-26T18:00:00   ITA           12                  Lazio  41.892770   
49  2020-02-26T18:0

In [ ]:
import numpy as np
from numpy import linalg as LA

# Our data
A = np.array([[1, 4, 16], [1, 0, 0], [1, 1, 1]])

y = np.array([[5], [1], [3]])

theta = LA.lstsq(A, y)

print(theta)


(array([[ 1.        ],
       [ 2.33333333],
       [-0.33333333]]), array([], dtype=float64), 3, array([16.5718975 ,  1.45791727,  0.49667938]))


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  if __name__ == '__main__':


In [ ]:
from sklearn.metrics import mean_squared_error

y_actual = [11,27,41]

y_predicted = [69,102,136]

rms = mean_squared_error(y_actual, y_predicted, squared=False)
rms


77.48978427293927